---
  # NOTE: This check assumes the /opt/influxdb/influx is a symlink
  - name: Check to make sure Influx isn't already present
    stat: path=/opt/influxdb/influx
    register: influx_installed

  - name: Download InfluxDB package
    command: curl -o /tmp/influx.deb http://influxdb.s3.amazonaws.com/influxdb_0.9.2_amd64.deb
    args:
      creates: /tmp/influx.deb
    when: influx_installed.stat.islnk is not defined or influx_installed.stat.islnk == False

  - name: Install InfluxDB packages (if not installed)
    apt: deb=/tmp/influx.deb
    when: influx_installed.stat.islnk is not defined or influx_installed.stat.islnk == False

  - name: Start the InfluxDB service
    service: name=influxdb state=started

  # TODO: Don't pause if the service was already started
  - name: Give the InfluxDB service a few seconds to fully start
    pause: seconds=5

  - name: Check to see which databases already exist
    command: /opt/influxdb/influx -execute 'show databases'
    register: db_listing

  # TODO: Parameterize database name creation (instead of hardcoding)
  - name: Create sample database
    command: /opt/influxdb/influx -execute 'CREATE DATABASE my_sample_db'
    when: db_listing.stdout.find("my_sample_db") == -1

  - name: Load some test data into sample database
    uri:
      url: http://localhost:8086/write?db=my_sample_db
      method: POST
      body: "random_ints,host=server_{{ 10 | random }} value={{ 100 | random }}"
      status_code: 204
    with_sequence: start=1 end=10
